package com.ottu.customization

const val THEME_MAIN_TITLE_TEXT = "THEME_MAIN_TITLE_TEXT"
const val THEME_TITLE_TEXT = "THEME_TITLE_TEXT"
const val THEME_SUBTITLE_TEXT = "THEME_SUBTITLE_TEXT"
const val THEME_FEES_TITLE_TEXT = "THEME_FEES_TITLE_TEXT"
const val THEME_FEES_SUBTITLE_TEXT = "THEME_FEES_SUBTITLE_TEXT"
const val THEME_DATA_LABEL_TEXT = "THEME_DATA_LABEL_TEXT"
const val THEME_DATA_VALUE_TEXT = "THEME_DATA_VALUE_TEXT"
const val THEME_ERROR_MESSAGE_TEXT = "THEME_ERROR_MESSAGE_TEXT"
const val THEME_INPUT_FIELD = "THEME_INPUT_FIELD"
const val THEME_BUTTON = "THEME_BUTTON"
const val THEME_SELECTOR_BUTTON = "THEME_SELECTOR_BUTTON"
const val THEME_BACK_BUTTON = "THEME_BACK_BUTTON"
const val THEME_SWITCH = "THEME_SWITCH"
const val THEME_SHOW_MORE_BUTTON = "THEME_SHOW_MORE_BUTTON"
const val THEME_SDK_MARGINS = "THEME_SDK_MARGINS"
const val THEME_SDK_BACKGROUND_COLOR = "THEME_SDK_BACKGROUND_COLOR"
const val THEME_SDK_MODAL_BACKGROUND_COLOR = "THEME_SDK_MODAL_BACKGROUND_COLOR"
const val THEME_SDK_SELECTOR_ITEM_BACKGROUND_COLOR = "THEME_SDK_SELECTOR_ITEM_BACKGROUND_COLOR"
const val THEME_SDK_SELECTOR_ICON_COLOR = "THEME_SDK_SELECTOR_ICON_COLOR"
const val THEME_SDK_SAVE_PHONE_ICON_COLOR = "THEME_SDK_SAVE_PHONE_ICON_COLOR"

//Text Component
const val TEXT_COMPONENT_COLOR = "TEXT_COMPONENT_COLOR"
const val TEXT_COMPONENT_FONT_TYPE = "TEXT_COMPONENT_FONT_TYPE"

//Text Field Component
const val TEXT_FIELD_COMPONENT_BACKGROUND_COLOR = "TEXT_FIELD_COMPONENT_BACKGROUND_COLOR"
const val TEXT_FIELD_COMPONENT_PRIMARY_COLOR = "TEXT_FIELD_COMPONENT_PRIMARY_COLOR"
const val TEXT_FIELD_COMPONENT_FOCUSED_COLOR = "TEXT_FIELD_COMPONENT_FOCUSED_COLOR"
const val TEXT_FIELD_COMPONENT_INPUT_TEXT = "TEXT_FIELD_COMPONENT_INPUT_TEXT"
const val TEXT_FIELD_COMPONENT_ERROR_TEXT = "TEXT_FIELD_COMPONENT_ERROR_TEXT"

//Button Component
const val BUTTON_COMPONENT_COLOR = "BUTTON_COMPONENT_COLOR"
const val BUTTON_COMPONENT_TEXT_COLOR = "BUTTON_COMPONENT_TEXT_COLOR"
const val BUTTON_COMPONENT_FONT_TYPE = "BUTTON_COMPONENT_FONT_TYPE"

//Switch Component
const val SWITCH_COMPONENT_CHECKED_THUMB_COLOR = "SWITCH_COMPONENT_CHECKED_THUMB_COLOR"
const val SWITCH_COMPONENT_UNCHECKED_THUMB_COLOR = "SWITCH_COMPONENT_UNCHECKED_THUMB_COLOR"
const val SWITCH_COMPONENT_CHECKED_TRACK_COLOR = "SWITCH_COMPONENT_CHECKED_TRACK_COLOR"
const val SWITCH_COMPONENT_UNCHECKED_TRACK_COLOR = "SWITCH_COMPONENT_UNCHECKED_TRACK_COLOR"
const val SWITCH_COMPONENT_CHECKED_DECORATION_COLOR = "SWITCH_COMPONENT_CHECKED_DECORATION_COLOR"
const val SWITCH_COMPONENT_UNCHECKED_DECORATION_COLOR =
    "SWITCH_COMPONENT_UNCHECKED_DECORATION_COLOR"

//Margins
const val MARGIN_LEFT = "MARGIN_LEFT"
const val MARGIN_TOP = "MARGIN_TOP"
const val MARGIN_RIGHT = "MARGIN_RIGHT"
const val MARGIN_BOTTOM = "MARGIN_BOTTOM"

//Fonts
const val FONT_TYPE_INTER = "FONT_TYPE_INTER"
const val FONT_TYPE_MONTSERRAT = "FONT_TYPE_MONTSERRAT"
const val FONT_TYPE_MONTSERRAT_SEMIBOLD = "FONT_TYPE_MONTSERRAT_SEMIBOLD"
const val FONT_TYPE_POPPINS = "FONT_TYPE_POPPINS"
const val FONT_TYPE_POPPINS_SEMIBOLD = "FONT_TYPE_POPPINS_SEMIBOLD"
const val FONT_TYPE_ROBOTO = "FONT_TYPE_ROBOTO"
const val FONT_TYPE_ROBOTO_BOLD = "FONT_TYPE_ROBOTO_BOLD"
const val FONT_TYPE_SF_PRO = "FONT_TYPE_SF_PRO"
const val FONT_TYPE_SF_PRO_BOLD = "FONT_TYPE_SF_PRO_BOLD"

data class ComponentItem(
    val tag: String,
    val name: String,
)

fun getComponents(): List<ComponentItem> {
    val components = mutableListOf<ComponentItem>().apply {
        add(ComponentItem(THEME_SDK_MARGINS, "Margins"))
        add(ComponentItem(THEME_SDK_BACKGROUND_COLOR, "SDK Background Color"))
        add(ComponentItem(THEME_SDK_MODAL_BACKGROUND_COLOR, "Modal Background Color"))
        add(ComponentItem(THEME_MAIN_TITLE_TEXT, "Main Title"))
        add(ComponentItem(THEME_TITLE_TEXT, "Title"))
        add(ComponentItem(THEME_SUBTITLE_TEXT, "Subtitle"))
        add(ComponentItem(THEME_FEES_TITLE_TEXT, "Fees Title"))
        add(ComponentItem(THEME_FEES_SUBTITLE_TEXT, "Fees Subtitle"))
        add(ComponentItem(THEME_DATA_LABEL_TEXT, "Data Label"))
        add(ComponentItem(THEME_DATA_VALUE_TEXT, "Data Value"))
        add(ComponentItem(THEME_ERROR_MESSAGE_TEXT, "Error Message"))
        add(ComponentItem(THEME_INPUT_FIELD, "Input Field"))
        add(ComponentItem(THEME_BUTTON, "Button"))
        add(ComponentItem(THEME_SELECTOR_BUTTON, "Selector Button"))
        add(ComponentItem(THEME_BACK_BUTTON, "Back Button"))
        add(ComponentItem(THEME_SHOW_MORE_BUTTON, "Show More"))
        add(ComponentItem(THEME_SWITCH, "Switch"))
        add(ComponentItem(THEME_SDK_SAVE_PHONE_ICON_COLOR, "Save Phone Number Icon Color"))
        add(ComponentItem(THEME_SDK_SELECTOR_ICON_COLOR, "Select Payment Icon Color"))
        add(
            ComponentItem(
                THEME_SDK_SELECTOR_ITEM_BACKGROUND_COLOR,
                "Select Payment Background Color"
            )
        )
    }

    return components
}